version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo "Install Pre-reqs"
      
  pre_build:
    commands:
      - npm install
      
  build:
    commands:
      - echo "Sample node app"
  post_build:
    commands:
      - echo "Post Build commands"
